Testsuite: org.intalio.tempo.security.authentication.UserNotFoundExceptionTest
Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 0.007 sec

Testcase: testUserNotFoundException took 0.001 sec
